# 添加到 [filter_local] 顶部，不是完整配置。
host-suffix,douyincdn.com,direct
host-suffix,douyinliving.com,direct
host-suffix,douyinvod.com,direct
host-suffix,douyinpic.com,direct
host-suffix,bytegecko.com,direct
host-suffix,byteeffecttos.com,direct
host-suffix,byteimg.com,direct
host-suffix,ecombdimg.com,direct
host-suffix,bytehwm.com,direct
host-suffix,bytecdn.com,direct
host-suffix,zjcdn.com,direct
host-keyword,awememusicpgc,direct
host,v9-awememusicpgc.amemv.com,direct
host-suffix,snssdk.com,Douyin-IP-Proxy
host-suffix,amemv.com,Douyin-IP-Proxy
